org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.jvmargs=-Xmx2g -XX:MaxMetaspaceSize=512m -XX:+HeapDumpOnOutOfMemoryError -Dfile.encoding=UTF-8 --add-opens java.base/java.io=ALL-UNNAMED --add-opens java.base/java.util=ALL-UNNAMED --add-opens java.base/java.lang=ALL-UNNAMED --add-opens java.base/java.util.concurrent=ALL-UNNAMED --add-opens java.base/java.net=ALL-UNNAMED
#systemProp.http.proxyHost=172.21.83.241
#systemProp.http.proxyPort=80
#systemProp.https.proxyHost=172.21.83.241
#systemProp.https.proxyPort=80
# Enabled parallel sync for Gradle 9.4+
org.gradle.tooling.parallel=true

android.useAndroidX=true
android.enableJetifier=true
